- name: Install Vagrant
  hosts: localhost
  connection: local
  become: yes
  vars:
    requested: "{{version | default('2.2.7')}}"
  tasks:

  - name: Check version of installed Go
    shell: vagrant -v | awk '{print $2}'
    register: installed
    changed_when: false

  - name: Compare installed version to requested
    debug:
      msg: Installed = {{installed.stdout}}, Requested = {{requested}}

  - name: Installing VirtualBox deb packages
    apt:
      pkg:
        - VirtualBox
        - virtualbox-guest-additions
    when:
      - ansible_pkg_mgr == 'apt'

  - name: Installing VirtualBox dnf packages
    dnf:
      name:
        - VirtualBox
        - virtualbox-guest-additions
    when:
      - ansible_pkg_mgr == 'dnf'

  - name: Installing deb package
    apt:
      deb: https://releases.hashicorp.com/vagrant/{{requested}}/vagrant_{{requested}}_x86_64.deb
    when:
      - ansible_pkg_mgr == 'apt'
      - installed.stdout != requested

  - name: Installing dnf packages
    dnf:
      name: https://releases.hashicorp.com/vagrant/{{requested}}/vagrant_{{requested}}_x86_64.rpm
      state: latest
    when:
      - ansible_pkg_mgr == 'dnf' or ansible_pkg_mgr == 'yum'
      - installed.stdout != requested
