- name: Install packages with apt
  hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: Removing packages
    apt:
      pkg:
        - lightdm
        - nano
        - vim-tiny
        - vim-common
        - vim-runtime
        - plymouth
        - curl # installed with nix
        - rsync # installed with nix
        - git # installed with nix
      state: absent
      purge: yes
      autoremove: yes
      autoclean: yes
  - name: Upgrade all packages
    apt:
      upgrade: dist
      update_cache: yes
  - name: Installing packages
    apt:
      pkg:
        - acpi
        - aptitude
        - cups
        - cups-pdf
        - ed
        - flatpak
        - fortunes-off
        - foomatic-db
        - gdebi
        - hplip
        - intel-microcode
        - network-manager-fortisslvpn
        - network-manager-openconnect
        - network-manager-fortisslvpn-gnome
        - network-manager-openconnect-gnome
        - openconnect
        - openfortivpn
        - powertop
        - printer-driver-hpcups
        - qemu-kvm
        - qemu-utils
        - qemu-system
        - snapd
        - thermald
        - tlp
        - virt-manager
        - xautolock
        - xbacklight
        - xclip
        - xfonts-terminus
        - xidle
        - xinput
        - xorg
        - xsel
        - xterm
        - zsh
      state: present
