- name: Install packages with apt
  hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: Removing packages
    apt:
      pkg:
        - sddm
        - lightdm
        - nano
        # - vim-tiny
        # - vim-common
        # - vim-runtime
        - plymouth
      state: absent
      purge: yes
      autoremove: yes
      autoclean: yes
  - name: Installing packages
    apt:
      default_release: "{{ansible_distribution_release + '-backports'}}"
      update_cache: yes
      pkg:
        - acpi
        - aptitude
        - build-essential
        - cups
        - cups-pdf
        - curl
        - ed
        # - flatpak
        - fortunes-off
        - foomatic-db
        - gdebi
        - git
        - hplip
        - intel-microcode
        - mg
        - network-manager
        - network-manager-fortisslvpn
        - network-manager-openconnect
        - network-manager-fortisslvpn-gnome
        - network-manager-openconnect-gnome
        - openconnect
        - openfortivpn
        - powertop
        - printer-driver-hpcups
        - qemu-kvm
        - qemu-utils
        - qemu-system
        - rsync
        - slock
        - snapd
        - thermald
        - tlp
        - virt-manager
        - xautolock
        - xbacklight
        - xclip
        - xfonts-terminus
        - xidle
        - xinput
        - xorg
        - xsel
        - xterm
        - zsh
      state: present
