- name: Clone git repositories
  hosts: all
  become: no
  tasks:
    - name: Clone bin repo
      git:
        repo: git@gitlab.com:tspub/bin.git
        version: master
        dest: "{{ansible_env.HOME}}/src/tspub/bin"
        accept_hostkey: yes
    - name: Clone emacs repo
      git:
        repo: git@gitlab.com:tspub/etc/emacs.git
        version: master
        dest: "{{ansible_env.HOME}}/src/tspub/etc/emacs"
        accept_hostkey: yes
    - name: Clone nix repo
      git:
        repo: git@gitlab.com:tspub/devops/nix.git
        version: master
        dest: "{{ansible_env.HOME}}/src/tspub/devops/nix"
        accept_hostkey: yes
    - name: Clone ansible repo
      git:
        repo: git@gitlab.com:tspub/devops/ansible.git
        version: master
        dest: "{{ansible_env.HOME}}/src/tspub/devops/ansible"
        accept_hostkey: yes
    - name: Clone lazygit repo
      git:
        repo: git@gitlab.com:tspub/js/lazygit.git
        version: master
        dest: "{{ansible_env.HOME}}/src/tspub/js/lazygit"
        accept_hostkey: yes
    - name: Clone personal notes repo
      git:
        repo: git@gitlab.com:tsprv/org/personal.git
        version: master
        dest: "{{ansible_env.HOME}}/src/tsprv/org/personal"
        accept_hostkey: yes
    - name: Clone work notes repo
      git:
        repo: git@gitlab.com:tsprv/org/work.git
        version: master
        dest: "{{ansible_env.HOME}}/src/tsprv/org/work"
        accept_hostkey: yes

    - name: Symlink ansible repo to $HOME/ansible
      file:
        src: "{{ansible_env.HOME}}/src/tspub/devops/ansible"
        dest: "{{ansible_env.HOME}}/ansible"
        state: link
        force: yes
    - name: Symlink bin repo to $HOME/bin
      file:
        src: "{{ansible_env.HOME}}/src/tspub/bin"
        dest: "{{ansible_env.HOME}}/bin"
        state: link
        force: yes
    - name: Symlink etc group to $HOME/etc
      file:
        src: "{{ansible_env.HOME}}/src/tspub/etc"
        dest: "{{ansible_env.HOME}}/etc"
        state: link
        force: yes
    - name: Symlink org group to $HOME/org
      file:
        src: "{{ansible_env.HOME}}/src/tsprv/org"
        dest: "{{ansible_env.HOME}}/org"
        state: link
        force: yes
    - name: Symlink nix repo to $HOME/nix
      file:
        src: "{{ansible_env.HOME}}/src/tspub/devops/nix"
        dest: "{{ansible_env.HOME}}/nix"
        state: link
        force: yes
    - name: Symlink nix repo pkgs dir to $HOME/.config/nixpkgs
      file:
        src: "{{ansible_env.HOME}}/src/tspub/devops/nix/pkgs"
        dest: "{{ansible_env.HOME}}/.config/nixpkgs"
        state: link
        force: yes
