- name: Clone git repositories
  hosts: localhost
  # vars_prompt:
  #   - name: token
  #     prompt: "Enter GitLab API token"
  #     private: yes
  vars:
    token: "{{ lookup('ini', 'token section=GitLab file=~/.gitforge.cfg') }}"
    dest: "{{ansible_env.HOME}}/src/gitlab/tslight"
    links:
      - { src: 'bin', dest: 'bin'}
      - { src: 'ansible', dest: 'ansible'}
      - { src: 'stumpwm', dest: '.stumpwm.d'}
  tasks:
    - name: Get all GitLab projects
      uri:
        url: "https://gitlab.com/api/v4/users/tslight/projects?per_page=100"
        method: GET
        validate_certs: no
        status_code:
          - 200
          - 201
          - 409
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{token}}"
      register: projects
    # - name: Print user projects
    #   debug:
    #     msg: "{{item.name}}"
    #   loop: "{{projects.json}}"
    #   loop_control:
    #     label: "{{item.name}}"
    - name: Cloning GitLab repos to {{dest}}
      git:
        repo: "git@gitlab.com:tslight/{{item.name}}.git"
        version: main
        dest: "{{dest}}/{{item.name}}"
        accept_hostkey: yes
      loop: '{{projects.json}}'
      loop_control:
        label: "Cloning {{item.name}} to {{dest}}"
    - name: Symlink repos in {{dest}} to {{ansible_env.HOME}}
      file:
        src: "{{dest}}/{{item.src}}"
        dest: "{{ansible_env.HOME}}/{{item.dest}}"
        state: link
        force: yes
      loop: '{{links}}'
