- name: Clone git repositories
  hosts: localhost
  vars:
    repos:
      - 'tslight/secrets'
      - 'tslight/personal'
      - 'tslight/work'
      - 'tslight/bin'
      - 'tslight/ansible'
      - 'tslight/etc'
      - 'tslight/cv'
      - 'tslight/emacs'
      - 'tslight/dotfiles'
      - 'tslight/lazygit.el'
      - 'tslight/lazygit.js'
      - 'tslight/stumpwm'
      - 'tslight/gitforge'
    links:
      - { src: 'tslight/bin', dest: 'bin'}
      - { src: 'tslight/ansible', dest: 'ansible'}
      - { src: 'tslight/stumpwm', dest: '.stumpwm.d'}
  tasks:

    - name: Installing apt packages
      become: yes
      apt:
        pkg: git
        state: latest
      when: ansible_pkg_mgr == 'apt'

    - name: Installing dnf packages
      become: yes
      dnf:
        name: git
        state: latest
      when: ansible_pkg_mgr == 'dnf'

    - name: Installing pacman packages
      become: yes
      pacman:
        name: git
        state: latest
      when: ansible_pkg_mgr == 'pacman'

    - name: Cloning GitLab repos to {{ansible_env.HOME}}/src/gitlab
      git:
        repo: "git@gitlab.com:{{item}}.git"
        version: main
        dest: "{{ansible_env.HOME}}/src/gitlab/{{item}}"
        accept_hostkey: yes
      loop: '{{repos}}'

    - name: Symlink repos to {{ansible_env.HOME}}
      file:
        src: "{{ansible_env.HOME}}/src/gitlab/{{item.src}}"
        dest: "{{ansible_env.HOME}}/{{item.dest}}"
        state: link
        force: yes
      loop: '{{links}}'
