- name: Install jumpapp from git
  hosts: localhost
  become: yes
  tasks:
    - name: Installing apt packages
      become: yes
      apt:
        pkg: [git, wmctrl, xdotool]
        state: latest
      when: ansible_pkg_mgr == 'apt'

    - name: Installing dnf packages
      become: yes
      dnf:
        name: [git, wmctrl, xdotool]
        state: latest
      when: ansible_pkg_mgr == 'dnf'

    - name: Installing pacman packages
      become: yes
      pacman:
        name: [git, wmctrl, xdotool]
        state: latest
      when: ansible_pkg_mgr == 'pacman'

    - name: Clone repos
      git:
        repo: 'https://github.com/mkropat/jumpapp.git'
        version: master
        dest: '{{ansible_env.HOME}}/src/jumpapp'
        accept_hostkey: yes
    - name: install jumpapp
      command: cp '{{ansible_env.HOME}}/src/jumpapp/jumpapp' /usr/local/bin
