- name: Install snaps
  hosts: localhost
  become: yes
  tasks:

  - name: Installing snap with apt
    apt:
      update_cache: yes
      pkg: snapd
      state: latest
    when: ansible_pkg_mgr == 'apt'

  - name: Installing snap with dnf
    dnf:
      update_cache: yes
      name: snapd
      state: latest
    when: ansible_pkg_mgr == 'dnf'

  - name: Symlinking /var/lib/snapd/snap to /snap
    file:
      src: /var/lib/snapd/snap
      dest: /snap
      state: link
    when: ansible_pkg_mgr == 'dnf' or ansible_pkg_mgr == 'pacman'

  - name: Enable apparmor systemd service
    systemd:
      name: apparmor
      enabled: yes
      state: started
    when: ansible_pkg_mgr == 'pacman'

  - name: Enable snapd.apparmor service
    systemd:
      name: snapd.apparmor
      enabled: yes
      state: started
    when: ansible_pkg_mgr == 'pacman'

  - name: Enable snapd socket
    systemd:
      name: snapd.socket
      enabled: yes
      state: started
    when: ansible_pkg_mgr == 'pacman'

  - name: Installing classic snaps
    snap:
      name:
        - powershell
        - powershell-preview
      classic: yes
      state: present

  - name: Installing normal snaps
    snap:
      name:
        - fast
        # - pulsemixer
        # - shellcheck
      state: present
