- name: Install Go
  hosts: all
  become: yes
  vars:
    go_version: "1.17"
    go_path: /usr/local
    golangci-lint_version: "1.43.0"
    gotestsum_version: "1.7.0"
  tasks:
  - name: Delete old Go
    file:
      path: '{{go_path}}/go'
      state: absent
  - name: Download & extract Go
    unarchive:
      src: "https://golang.org/dl/go{{go_version}}.linux-amd64.tar.gz"
      dest: '{{go_path}}'
      remote_src: yes
  - name: Add Go to /etc/profile
    blockinfile:
      path: /etc/profile
      backup: yes
      marker: "# {mark} Golang config"
      block: |
        export GOPATH=$HOME/go
        export GOROOT={{go_path}}/go
        export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
  - name: Install Golang CI Lint tool
    unarchive:
      src: "https://github.com/golangci/golangci-lint/releases/download/v{{golangci-lint_version}}/golangci-lint-{{golangci-lint_version}}-linux-amd64.tar.gz"
      dest: /usr/local/bin
      remote_src: yes
      extra_opts:
        - --strip-components=1
  - name: Install Golang Test Sum tool
    unarchive:
      src: "https://github.com/gotestyourself/gotestsum/releases/download/v{{gotestsum_version}}/gotestsum_{{gotestsum_version}}_linux_amd64.tar.gz"
      dest: /usr/local/bin
      remote_src: yes
