- name: Install Go
  hosts: all
  become: yes
  vars:
    go_version: "1.17"
    go_path: /usr/local
    golangcilint_version: "1.43.0"
    gotestsum_version: "1.7.0"
    arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
    os: "{{ansible_os_family|lower}}"
    url: "https://golang.org/dl/go{{go_version}}.{{os}}-{{arch}}.tar.gz"
  tasks:
  - debug:
      msg:
        - "Architecture = {{arch}}"
        - "Operating System = {{os}}"
  - name: Delete old Go
    file:
      path: '{{go_path}}/go'
      state: absent
  - name: Download & extract Go
    unarchive:
      src: "{{url}}"
      dest: '{{go_path}}'
      remote_src: yes
  - name: Add Go to /etc/profile
    blockinfile:
      path: "{{ansible_env.HOME}}/.profile"
      create: yes
      backup: yes
      marker: "# {mark} Golang config"
      block: |
        export GOPATH=$HOME/go
        export GOROOT={{go_path}}/go
        export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
  - name: Install Golang CI Lint tool
    unarchive:
      src: "https://github.com/golangci/golangci-lint/releases/download/v{{golangcilint_version}}/golangci-lint-{{golangcilint_version}}-{{os}}-{{arch}}.tar.gz"
      dest: /usr/local/bin
      remote_src: yes
      extra_opts:
        - --strip-components=1
  - name: Install Golang Test Sum tool
    unarchive:
      src: "https://github.com/gotestyourself/gotestsum/releases/download/v{{gotestsum_version}}/gotestsum_{{gotestsum_version}}_{{os}}_{{arch}}.tar.gz"
      dest: /usr/local/bin
      remote_src: yes
  - name: Install gopls
    shell: |
      source "$HOME/.profile"
      go install golang.org/x/tools/gopls@latest
