- name: Install Go
  hosts: all
  become: yes
  vars:
    version: "1.17"
    go_path: /usr/local
  tasks:
  - name: Delete old Go
    file:
      path: '{{go_path}}/go'
      state: absent
  - name: Download & extract Go
    unarchive:
      src: "https://golang.org/dl/go{{version}}.linux-amd64.tar.gz"
      dest: '{{go_path}}'
      remote_src: yes
  - name: Add Go to /etc/profile
    blockinfile:
      path: /etc/profile
      backup: yes
      marker: "# {mark} Golang config"
      block: |
        export GOROOT={{go_path}}/go
        export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
