- name: Install the latest Terraform
  hosts: all
  vars:
    version: "0.15.5"
    arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
  tasks:
  - debug:
      msg: "arch is {{arch}}"
  - name: Download & extract Terraform {{version}}
    become: yes
    unarchive:
      src: 'https://releases.hashicorp.com/terraform/{{version}}/terraform_{{version}}_linux_{{arch}}.zip'
      dest: /usr/local/bin
      remote_src: yes
