- name: Install the latest Terraform
  hosts: all
  vars:
    ver: "{{ version | default ('1.0.4') }}"
    requested: "{{'v' + version | default('1.0.4') }}"
  tasks:
  - name: Check version of installed terraform
    shell: terraform version | head -n 1 | awk '{print $2}'
    register: current
    changed_when: false
  - name: Compare installed version to requested
    debug:
      msg: Installed = {{current.stdout}}, Requested = {{requested}}
  - name: Download & extract Terraform {{ver}}
    become: yes
    unarchive:
      src: 'https://releases.hashicorp.com/terraform/{{ver}}/terraform_{{ver}}_linux_amd64.zip'
      dest: /usr/local/bin
      remote_src: yes
    when: current.stdout != requested
